Repository livesport-tv/util, pull requests merged in 2022-04, with the labels that each got.

#16 Release/v0.6.0
  CHANGELOG.md
  README.md
  uu/id.go
  uu/id_test.go
Labels: feature

#17 Code coverage badge
  .github/workflows/tests.yml
  Makefile
  README.md
Labels: documentation

#18 Release/v0.7.0
  CHANGELOG.md
  date/date.go
  date/date_test.go
  date/filter.go
  date/filter_test.go
  roman/parse.go
  roman/roman.go
  roman/roman_test.go
  sem/compare.go
  sem/errors.go
  sem/latest.go
  sem/version.go
  sem/version_test.go
  size/parse.go
  size/size.go
  size/size_test.go
  uu/errors.go
  uu/errors_test.go
  uu/format.go
  uu/format_test.go
  uu/id.go
  uu/id_test.go
  uu/parse.go
  uu/parse_test.go
  uu/random.go
  uu/random_test.go
Labels: feature

#19 fix(test): allow to test pointer types
  CHANGELOG.md
  test/binary.go
  test/json.go
  test/test.go
  test/test_test.go
  test/text.go
Labels: bug, feature
